# ========================
# Project Configuration
# ========================

paths:
  project_root: .
  data_root: ./mmact_data
  video_root: ${paths.data_root}/trimmed_camera1/video/test
  sensor_root: ${paths.data_root}/trimmed_sensor/sensor/test
  annotation_root: ${paths.data_root}/annotation
  report_root: ./report

# ========================
# Training Configuration
# ========================
training:
  device: cuda
  batch_size: 8
  embedding_dim: 256
  lr: 1e-4
  num_epochs: 150
  yolo_weight: ./utils/yolov8m.pt
  save_dir: ./checkpoints